root-gg/plik

- client/config/config.go
- client/plik.go
- test/file/filename_spec.js
- test/file/multi_file_spec.js
Fix a bug in tests where filename variable was not right
Add a --quiet arg to client to print only urls
> Fix test + Quiet argument in client

- client/archive/archive.go
- client/archive/tar/tar.go
- client/archive/zip/zip.go
- client/config/config.go
- client/crypto/crypto.go
- client/crypto/openssl/openssl.go
- client/crypto/pgp/pgp.go
- client/plik.go
- server/common/context.go
- server/common/result.go
- server/data_backend/dataBackend.go
- server/data_backend/file/file.go
- server/data_backend/swift/swift.go
- server/data_backend/weedfs/weedfs.go
- server/metadata_backend/file/file.go
- server/metadata_backend/mongo/mongo.go
- server/plik.go
- server/plik_test.go
- server/shorten_backend/isgd/isgd.go
- server/shorten_backend/w000t/w000t.go
govet : correcting faults in code (ex fmt.Sprintf with no variables)
goimports : go fmt + reorder imports
golint : code best pratices
> govet + goimports + begin golint

- client/config/config.go
Fix: Wrong option set in client	adeb6b6
Fix: Detect http redirections to compute right url in client
> Merge 1.0.2 last commits into 1.1

- client/plik.go
- client/test_downgrade.sh
- client/test_upgrade.sh
Client update with /version
Client upgrade test script
Client downgrade test script
> Client update with /version and test scripts

- Makefile
- README.md
- client/plik.go
- server/metadataBackend/file/file.go
- server/public/index.html
Changelog : 
- Fix : Bug when an upload metadata was missing in cleaning routine for file metadata backend
- Fix : Reload issue on plik logo
- Fix : Typo in client README
- Fix : Download client updates on tmp directory
> Version 1.1.1

- README.md
- server/public/index.html
- server/public/package.json
- updated Go version from 1.7.4 to 1.8.3
- fixed README.md markdown syntax issues
- fixed consistency usage of double quotes in index.html (webapp)
- updated webapp build dependencies
> Minor changes

- server/handlers/getFile.go
https://github.com/root-gg/plik/issues/233
> Allow to play mp3/mp4 inside the browser

- client/plik.go
> Add ProxyFromEnvironment in http.Transport configuration.

- server/handlers/google.go
cf https://github.com/root-gg/plik/issues/301
> fix Google user not found in database

- webapp/partials/main.html
Hi,
Here are a few minor fixes to improve the interface.
> Reword some tooltips, fix typos

- documentation/docker.md
It took me a while to figure out how to configure this project with complete persistence in docker-compose. I thought I'd share my results.
> Provide a usage example for docker-compose

- webapp/js/app.js
- webapp/js/ctrl/main.js
- webapp/js/lib/api.js
- webapp/js/lib/paste.js
- webapp/partials/main.html
Address https://github.com/root-gg/plik/issues/392
> Fix paste listener

- server/middleware/context.go
- server/middleware/context_test.go
- server/middleware/log.go
- server/middleware/recover.go
- server/middleware/recover_test.go
- server/server/server.go
Log response status code and elapsed duration
> Log response status code and duration

- server/common/config.go
- server/context/errors.go
- server/plikd.cfg
https://github.com/root-gg/plik/issues/396
> Configurable log level

- server/common/config.go
- server/plikd.cfg
- server/server/server.go
https://github.com/root-gg/plik/issues/338
> Make static content directories configurable

- .dockerignore
- .github/workflows/master.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- Dockerfile
- Makefile
- README.md
- releaser/release.sh
- releaser/releaser.sh
- rootgg/plik is now multiarch
- rootgg/plik-linux-arch images are now deprecated
> Build multiarch Docker images with Docker buildx

- Makefile
- releaser/release.sh
- releaser/releaser.sh
- server/gen_build_info.sh
> Add FreeBSD support for compilation

- server/common/config.go
- server/common/feature_flags.go
- server/common/feature_flags_test.go
- server/plikd.cfg
- webapp/index.html
- webapp/js/ctrl/main.js
- webapp/js/ctrl/menu.js
Add two new feature flags :
```
FeatureClients        = "enabled"      # Display the clients download button in the web UI
FeatureGithub         = "enabled"      # Display the source code link in the web UI
```
> New feature flags to enable/disable clients and Github links in the web UI

- server/common/authentication.go
- server/common/authentication_test.go
- server/common/config.go
- server/common/config_test.go
- server/middleware/authenticate.go
- server/middleware/authenticate_test.go
- server/plikd.cfg
- server/server/server.go
Also fix authentication cookies path value when web server root path is
set
> Add authentication session timeout (#423)

- server/cmd/user.go
> Fix create user password parameter (#489)
